name: AGT
version: "0.3"
license: "GPL-2.0-or-later"
date: 2022-10-22
description: |
    Algebraic Graph Theory

authors:
    - name: Rhys J. Evans
      url: https://rhysje00.github.io/

maintainers:
    - name: Rhys J. Evans
      url: https://rhysje00.github.io/

GAP: ">= 4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "GRAPE"
      version: ">= 4.8"
    - name: "design"
      version: ">= 1.7"
    - name: "Digraphs"
      version: ">= 0.15.2"

www: https://gap-packages.github.io/agt
readme: README.md
packageinfo: https://gap-packages.github.io/agt/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/AGT/releases/download/v0.3/AGT-0.3.tar.gz

abstract: |
    The <span class="pkgname">AGT</span> package provides functionality to      inspect combinatorial and algebraic properties of graphs in GRAPE format.      It also provides a library  strongly regular graphs on at most 40 vertices,     and several graph constructions

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    strongly regular, edge-regular, eigenvalues, clique, induced subgraphs.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Eva22</span>]   <b class='BibAuthor'>Evans, R. J.</b>,
     <i class='BibTitle'>AGT, Algebraic Graph Theory,
             Version 0.3</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/agt">https://gap-packages.github.io/agt</a></span>.
    </p>
    

bibtex: |
    @misc{ AGT0.3,
      author =           {Evans, R. J.},
      title =            {{AGT}, Algebraic Graph Theory, {V}ersion 0.3},
      month =            {Oct},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href             {https://gap-packages.github.io/agt}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{agt}}},
      keywords =         {strongly  regular;  edge-regular; eigenvalues; clique;
                          induced subgraphs},
      printedkey =       {Eva22}
    }

